package com.blog.hbm.pojo;
// Generated 18 de mai de 2022 15:01:40 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Localizacao generated by hbm2java
 */
@Entity
@Table(name="localizacao"
    ,schema="public"
)
public class Localizacao  implements java.io.Serializable {


     private long id;
     private Double latitude;
     private Double longitude;
     private Set<Restaurante> restaurantes = new HashSet<Restaurante>(0);

    public Localizacao() {
    }

	
    public Localizacao(long id) {
        this.id = id;
    }
    public Localizacao(long id, Double latitude, Double longitude, Set<Restaurante> restaurantes) {
       this.id = id;
       this.latitude = latitude;
       this.longitude = longitude;
       this.restaurantes = restaurantes;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="latitude", precision=17, scale=17)
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
    
    @Column(name="longitude", precision=17, scale=17)
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="localizacao")
    public Set<Restaurante> getRestaurantes() {
        return this.restaurantes;
    }
    
    public void setRestaurantes(Set<Restaurante> restaurantes) {
        this.restaurantes = restaurantes;
    }




}


