package com.blog.hbm.pojo;
// Generated 18 de mai de 2022 15:01:40 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Prato generated by hbm2java
 */
@Entity
@Table(name="prato"
    ,schema="public"
)
public class Prato  implements java.io.Serializable {


     private long id;
     private Restaurante restaurante;
     private String descricao;
     private String nome;
     private BigDecimal preco;

    public Prato() {
    }

	
    public Prato(long id) {
        this.id = id;
    }
    public Prato(long id, Restaurante restaurante, String descricao, String nome, BigDecimal preco) {
       this.id = id;
       this.restaurante = restaurante;
       this.descricao = descricao;
       this.nome = nome;
       this.preco = preco;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="restaurante_id")
    public Restaurante getRestaurante() {
        return this.restaurante;
    }
    
    public void setRestaurante(Restaurante restaurante) {
        this.restaurante = restaurante;
    }
    
    @Column(name="descricao")
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    
    @Column(name="nome")
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    @Column(name="preco")
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }




}


