package com.blog.hbm.pojo;
// Generated 18 de mai de 2022 15:01:40 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Restaurante generated by hbm2java
 */
@Entity
@Table(name="restaurante"
    ,schema="public"
)
public class Restaurante  implements java.io.Serializable {


     private long id;
     private Localizacao localizacao;
     private String cnpj;
     private Date dataatualizacao;
     private Date datacriacao;
     private String nome;
     private String proprietario;
     private Set<Prato> pratos = new HashSet<Prato>(0);

    public Restaurante() {
    }

	
    public Restaurante(long id) {
        this.id = id;
    }
    public Restaurante(long id, Localizacao localizacao, String cnpj, Date dataatualizacao, Date datacriacao, String nome, String proprietario, Set<Prato> pratos) {
       this.id = id;
       this.localizacao = localizacao;
       this.cnpj = cnpj;
       this.dataatualizacao = dataatualizacao;
       this.datacriacao = datacriacao;
       this.nome = nome;
       this.proprietario = proprietario;
       this.pratos = pratos;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="localizacao_id")
    public Localizacao getLocalizacao() {
        return this.localizacao;
    }
    
    public void setLocalizacao(Localizacao localizacao) {
        this.localizacao = localizacao;
    }
    
    @Column(name="cnpj")
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataatualizacao", length=29)
    public Date getDataatualizacao() {
        return this.dataatualizacao;
    }
    
    public void setDataatualizacao(Date dataatualizacao) {
        this.dataatualizacao = dataatualizacao;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datacriacao", length=29)
    public Date getDatacriacao() {
        return this.datacriacao;
    }
    
    public void setDatacriacao(Date datacriacao) {
        this.datacriacao = datacriacao;
    }
    
    @Column(name="nome")
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    
    @Column(name="proprietario")
    public String getProprietario() {
        return this.proprietario;
    }
    
    public void setProprietario(String proprietario) {
        this.proprietario = proprietario;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="restaurante")
    public Set<Prato> getPratos() {
        return this.pratos;
    }
    
    public void setPratos(Set<Prato> pratos) {
        this.pratos = pratos;
    }




}


